# Generated by Django 5.2.7 on 2026-04-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manual80GSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=100)),
                ('donor_email', models.EmailField(max_length=254)),
                ('donor_mobile', models.CharField(max_length=20)),
                ('service_date', models.DateField()),
                ('donation_date', models.DateField()),
                ('donor_pan', models.CharField(max_length=10)),
                ('donation_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donor_address', models.TextField()),
                ('receipt_no', models.CharField(max_length=50)),
                ('mode_of_donation', models.CharField(max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
