# Generated by Django 5.2.7 on 2026-06-15 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0002_remove_services_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=200)),
                ('donor_mobile', models.CharField(max_length=15)),
                ('donor_email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('service_date', models.DateField(blank=True, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('donation_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='dashboard.services')),
            ],
        ),
    ]
