# Generated by Django 5.2.7 on 2026-06-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
