# Generated by Django 5.2.7 on 2026-06-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_volunteer_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedonation',
            name='easebuzz_payment_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicedonation',
            name='easebuzz_payment_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicedonation',
            name='easebuzz_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicedonation',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicedonation',
            name='txnid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
