# Generated by Django 5.2.7 on 2026-07-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_servicedonation_easebuzz_payment_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=255)),
                ('donor_email', models.EmailField(max_length=254)),
                ('donor_mobile', models.CharField(max_length=15)),
                ('txnid', models.CharField(blank=True, max_length=100, null=True)),
                ('service_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('breakfast_selected', models.BooleanField(default=False)),
                ('lunch_selected', models.BooleanField(default=False)),
                ('dinner_selected', models.BooleanField(default=False)),
                ('lunch_type', models.CharField(blank=True, choices=[('pure_veg', 'Pure Veg'), ('non_veg', 'Non Veg')], max_length=20, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('home_name', models.CharField(blank=True, max_length=50, null=True)),
                ('easebuzz_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('easebuzz_payment_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('easebuzz_payment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('receipt_no', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='servicedonation',
            name='receipt_no',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='servicedonation',
            name='service_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
