# Generated by Django 5.2.7 on 2026-07-13 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_home'),
        ('website', '0006_homedonation_servicedonation_receipt_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedonation',
            name='service_name',
        ),
        migrations.AddField(
            model_name='homedonation',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='dashboard.home'),
        ),
    ]
