# Generated by Django 5.2.7 on 2026-07-01 05:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0003_rm_rmloginhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='RMPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rm_code', models.CharField(max_length=4)),
                ('rm_name', models.CharField(max_length=100)),
                ('qr_name', models.CharField(blank=True, max_length=150, null=True)),
                ('donor_name', models.CharField(max_length=100)),
                ('donor_email', models.EmailField(max_length=254)),
                ('donor_mobile', models.CharField(max_length=15)),
                ('donor_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donor_message', models.TextField(blank=True, null=True)),
                ('donor_address', models.TextField(blank=True, null=True)),
                ('receipt_no', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('package_type', models.CharField(blank=True, choices=[('birthday', 'Birthday Package'), ('food', 'Food Package')], max_length=20, null=True)),
                ('txnid', models.CharField(max_length=100, unique=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_rrn', models.CharField(blank=True, max_length=50, null=True)),
                ('easebuzz_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('easebuzz_payment_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('easebuzz_payment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=20, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QRDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('payment_mode', models.CharField(blank=True, max_length=20, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('unique_transaction_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('remitter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('remitter_upi', models.CharField(blank=True, max_length=100, null=True)),
                ('remitter_account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('remitter_ifsc', models.CharField(blank=True, max_length=20, null=True)),
                ('remitter_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('virtual_upi_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('virtual_label', models.CharField(blank=True, max_length=100, null=True)),
                ('qr_id', models.CharField(blank=True, max_length=100, null=True)),
                ('qr_name', models.CharField(blank=True, max_length=255, null=True)),
                ('qr_description', models.TextField(blank=True, null=True)),
                ('qr_notes', models.JSONField(blank=True, null=True)),
                ('rm_name', models.CharField(blank=True, max_length=100, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('bank_rrn', models.CharField(blank=True, max_length=100, null=True)),
                ('method', models.CharField(blank=True, max_length=50, null=True)),
                ('donor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('donor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('donor_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('donor_address', models.TextField(blank=True, null=True)),
                ('receipt_no', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('package_type', models.CharField(blank=True, choices=[('birthday', 'Birthday Package'), ('food', 'Food Package'), ('service', 'Service Package')], max_length=20, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=20, null=True)),
                ('rm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.rm')),
            ],
        ),
        migrations.CreateModel(
            name='RMGPayPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rm_code', models.CharField(max_length=4)),
                ('rm_name', models.CharField(max_length=100)),
                ('rm_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('donor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('donor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('donor_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('donor_address', models.TextField(blank=True, null=True)),
                ('donor_pan', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('gpay_reference_id', models.CharField(blank=True, db_index=True, help_text='UPI Ref / UTR / GPay Transaction ID', max_length=100, null=True)),
                ('payment_screenshot', models.ImageField(blank=True, help_text='Upload GPay payment screenshot', null=True, upload_to='gpay_screenshots/')),
                ('receipt_no', models.CharField(editable=False, max_length=25, unique=True)),
                ('package_type', models.CharField(blank=True, choices=[('birthday', 'Birthday Package'), ('food', 'Food Package'), ('service', 'Service'), ('other', 'Other')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpay_payments', to='dashboard.rm')),
            ],
        ),
    ]
