# Generated by Django 5.2.7 on 2026-07-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmgpaypayment',
            name='receipt_no',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
