# Generated by Django 5.2.7 on 2026-06-13 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='tag',
        ),
    ]
