# Generated by Django 5.2.7 on 2026-06-25 10:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_services_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='RM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rm_name', models.CharField(max_length=100)),
                ('rm_mob_no', models.CharField(max_length=15)),
                ('rm_email', models.EmailField(max_length=254)),
                ('rm_code', models.CharField(editable=False, max_length=4, unique=True)),
                ('rm_branch', models.CharField(blank=True, choices=[('madurai', 'Madurai'), ('chennai', 'Chennai'), ('bangalore', 'Bangalore')], max_length=20, null=True)),
                ('rm_gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('rm_password', models.CharField(blank=True, max_length=255, null=True)),
                ('virtual_label', models.CharField(blank=True, max_length=150, null=True)),
                ('target_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('active_whatsapp', models.BooleanField(default=False)),
                ('whatsapp_admin_enabled', models.BooleanField(default=False)),
                ('last_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('active_visitor_chat', models.BooleanField(default=False)),
                ('last_visitor_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('tl_name', models.CharField(blank=True, max_length=50, null=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr/')),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'active_whatsapp', 'whatsapp_admin_enabled'], name='dashboard_r_is_acti_bd5c97_idx'), models.Index(fields=['is_active', 'active_visitor_chat'], name='dashboard_r_is_acti_3c7875_idx')],
            },
        ),
        migrations.CreateModel(
            name='RMLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('rm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to='dashboard.rm')),
            ],
        ),
    ]
