# Generated by Django 5.2.7 on 2026-07-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rm_rmloginhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('members', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('home_image', models.ImageField(upload_to='home_images/')),
                ('map_embed', models.TextField(blank=True, help_text="Paste the Google Maps 'Embed a map' iframe code (or just its src URL) for this home's location.", null=True)),
                ('service_img1', models.ImageField(blank=True, null=True, upload_to='home_service_images/')),
                ('service_img2', models.ImageField(blank=True, null=True, upload_to='home_service_images/')),
                ('service_img3', models.ImageField(blank=True, null=True, upload_to='home_service_images/')),
                ('service_img4', models.ImageField(blank=True, null=True, upload_to='home_service_images/')),
                ('service_img5', models.ImageField(blank=True, null=True, upload_to='home_service_images/')),
            ],
        ),
    ]
