# Generated by Django 5.2.7 on 2026-06-29 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0003_rm_rmloginhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_preview', models.TextField(blank=True)),
                ('last_message_type', models.CharField(blank=True, max_length=10, null=True)),
                ('last_message_status', models.CharField(blank=True, max_length=10, null=True)),
                ('last_message_direction', models.CharField(blank=True, max_length=3, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_message_id', models.BigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='dashboard.rm')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='RMPortal.donor')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Incoming'), ('out', 'Outgoing')], max_length=3)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document')], default='text', max_length=10)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read')], default='sent', max_length=10)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='RMPortal.conversation')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='RMPortal.message')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='whatsapp_media/')),
                ('mime_type', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField()),
                ('wa_media_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='RMPortal.message')),
            ],
        ),
        migrations.CreateModel(
            name='VisitorConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('closed', 'Closed'), ('missed', 'Missed'), ('reassigned', 'Reassigned')], default='waiting', max_length=10)),
                ('missed_reason', models.CharField(blank=True, choices=[('no_rm', 'No RM available'), ('night_chat', 'Night hours'), ('rm_no_reply', 'RM did not reply'), ('visitor_no_msg', 'Visitor left without typing'), ('quickly_left', 'Visitor left within 5s'), ('stale_waiting', 'Stale waiting'), ('slow_response', 'RM did not reply in 30s')], db_index=True, max_length=16, null=True)),
                ('initiated_by', models.CharField(choices=[('visitor', 'Visitor'), ('rm', 'RM')], default='visitor', max_length=7)),
                ('unread_count_rm', models.PositiveIntegerField(default=0)),
                ('unread_count_visitor', models.PositiveIntegerField(default=0)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_preview', models.TextField(blank=True)),
                ('last_message_direction', models.CharField(blank=True, max_length=7, null=True)),
                ('visitor_first_message_at', models.DateTimeField(blank=True, null=True)),
                ('rm_first_response_at', models.DateTimeField(blank=True, null=True)),
                ('response_time_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('fallback_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('rm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_conversations', to='dashboard.rm')),
            ],
        ),
        migrations.CreateModel(
            name='VisitorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('visitor', 'Visitor to RM'), ('rm', 'RM to Visitor')], max_length=7)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File')], default='text', max_length=5)),
                ('body', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='visitor_media/')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='RMPortal.visitorconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('cookie_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('isp', models.CharField(blank=True, max_length=200, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('referrer', models.CharField(blank=True, max_length=500, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=100, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=100, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=100, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('total_time_seconds', models.PositiveIntegerField(default=0)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('is_online', models.BooleanField(default=True)),
                ('is_returning', models.BooleanField(default=False)),
                ('current_page', models.CharField(blank=True, max_length=500, null=True)),
                ('assigned_rm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_visitors', to='dashboard.rm')),
            ],
        ),
        migrations.CreateModel(
            name='VisitorPageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('page_title', models.CharField(blank=True, max_length=200, null=True)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='RMPortal.visitorsession')),
            ],
            options={
                'ordering': ['entered_at'],
            },
        ),
        migrations.AddField(
            model_name='visitorconversation',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_conversations', to='RMPortal.visitorsession'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['rm', 'status'], name='RMPortal_co_rm_id_aa85e9_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['rm', 'is_active'], name='RMPortal_co_rm_id_a39700_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['last_message_at'], name='RMPortal_co_last_me_844875_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='RMPortal_me_convers_ae9af7_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['external_id'], name='RMPortal_me_externa_392a3a_idx'),
        ),
        migrations.AddIndex(
            model_name='visitormessage',
            index=models.Index(fields=['conversation', 'created_at'], name='RMPortal_vi_convers_464163_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorsession',
            index=models.Index(fields=['ip_address'], name='RMPortal_vi_ip_addr_f4d54c_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorsession',
            index=models.Index(fields=['first_seen_at'], name='RMPortal_vi_first_s_6859eb_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorsession',
            index=models.Index(fields=['is_online'], name='RMPortal_vi_is_onli_f76211_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorpageview',
            index=models.Index(fields=['visitor', 'entered_at'], name='RMPortal_vi_visitor_e0b76c_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorconversation',
            index=models.Index(fields=['rm', 'status'], name='RMPortal_vi_rm_id_0a92e1_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorconversation',
            index=models.Index(fields=['visitor'], name='RMPortal_vi_visitor_7997e4_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorconversation',
            index=models.Index(fields=['last_message_at'], name='RMPortal_vi_last_me_0c69a7_idx'),
        ),
    ]
