# Generated by Django 5.2.3 on 2026-09-19 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMPortal', '0001_initial'),
        ('dashboard', '0004_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('wa_api_blocked', models.BooleanField(default=False)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('unblocked_at', models.DateTimeField(blank=True, null=True)),
                ('unblocked_by', models.CharField(blank=True, max_length=150)),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_contacts', to='dashboard.rm')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='RMPortal.donor')),
            ],
            options={
                'ordering': ['-blocked_at'],
                'indexes': [models.Index(fields=['donor', 'is_active'], name='RMPortal_bl_donor_i_802b65_idx')],
            },
        ),
    ]
