"""
Django settings for wengo project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/
For the full list of settings and values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from decouple import config
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-9q*@q8m%wyaxj5d$u3w#ezzx5==%+x_gs*gu9sq%0g+8q7yafn')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')

# Nginx terminates TLS and proxies to Daphne over plain HTTP, so Django must
# trust X-Forwarded-Proto to know the original request was HTTPS. Without this
# CSRF sees the request as http:// and rejects the browser's https:// Origin.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

# Django 4.0+ checks the Origin header against this list (scheme required).
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in config(
        'CSRF_TRUSTED_ORIGINS',
        default='https://wengo.org.in,https://www.wengo.org.in',
    ).split(',') if o.strip()
]


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'website',
    'dashboard',
    'receipt',
    'RMPortal',
    'easypay',
    'channels',
]

if DEBUG:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [config('REDIS_URL', default='redis://127.0.0.1:6379/2')],
            },
        },
    }

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'RMPortal.middleware.UpdateLastSeenMiddleware',
    'RMPortal.middleware.RMAuthMiddleware',
    'dashboard.middleware.DashboardNoCacheMiddleware',
]

SECURE_CROSS_ORIGIN_OPENER_POLICY = 'unsafe-none'
ROOT_URLCONF = 'wengo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'website' / 'templates',
            BASE_DIR / 'dashboard' / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'RMPortal.context_processors.rm_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'wengo.wsgi.application'
ASGI_APPLICATION = 'wengo.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='3306'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'  # ✅ Add this

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


EMAIL_BACKEND = config('EMAIL_BACKEND')
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_PORT = config('EMAIL_PORT', cast=int)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=False, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')


# WhatsApp Cloud API configuration
WA_ACCESS_TOKEN = config('WA_ACCESS_TOKEN', default='')
WA_PHONE_NUMBER_ID = config('WA_PHONE_NUMBER_ID', default='')
WA_APP_SECRET = config('WA_APP_SECRET', default='')
VERIFY_TOKEN = config('VERIFY_TOKEN', default='')
WA_DISPLAY_PHONE = config('WA_DISPLAY_PHONE', default='+91 90876 96777')
WA_DISPLAY_PHONE_LINK = config('WA_DISPLAY_PHONE_LINK', default='919087696777') 
WA_NUMBERS = {
    "madurai": {
        "phone_number_id": config('WA_PHONE_NUMBER_ID', default=''),
        "access_token": config('WA_ACCESS_TOKEN', default=''),
    },
    "chennai": {
        "phone_number_id": config('WA_PHONE_NUMBER_ID', default=''),
        "access_token": config('WA_ACCESS_TOKEN', default=''),
    },
    "bangalore": {
        "phone_number_id": config('WA_PHONE_NUMBER_ID_BLR', default=config('WA_PHONE_NUMBER_ID', default='')),
        "access_token": config('WA_ACCESS_TOKEN_BLR', default=config('WA_ACCESS_TOKEN', default='')),
    },
}

WA_FALLBACK_GREETING = config('WA_FALLBACK_GREETING', default=(
    "Hi! 👋 Welcome to WeNGO. For any support or queries, feel free to reach out. "
    "We're happy to help! 🙏"
))


#Production settings

EASEBUZZ_MERCHANT_KEY = config('EASEBUZZ_MERCHANT_KEY')
EASEBUZZ_SALT = config('EASEBUZZ_SALT')
EASEBUZZ_ENV = config('EASEBUZZ_ENV', default='prod')
EASEBUZZ_INITIATE_PAYMENT_URL = config('EASEBUZZ_INITIATE_PAYMENT_URL')


SESSION_COOKIE_AGE = 300  # 5 minutes for dashboard session timeout 
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

LOGIN_URL = '/rm/login'
LOGIN_REDIRECT_URL = '/rm/webchat/'

WA_FALLBACK_GREETING = (
    "Hi! 👋 Welcome to WeNGO. For any support or queries, feel free to reach out. "
    "We're happy to help! 🙏"
)
